M48
; DRILL file {KiCad (6.0.10-0)} date 2023 February 15, Wednesday 22:26:59
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-15T22:26:59+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X3.74Y-2.94
X3.74Y-3.76
X7.1Y-2.94
X7.1Y-3.76
T0
M30
